/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package userInterfaces;

import crudjava_2.Querys;
import crudjava_2.UserServices;
import javax.swing.JOptionPane;

/**
 *
 * @author Nog
 */
public class FormUpdate extends javax.swing.JDialog {

    /**
     * Creates new form formUpdate
     */
    public FormUpdate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
     
        initComponents();
        this.lblError.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainTitle = new javax.swing.JLabel();
        titleName = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputUser = new javax.swing.JTextField();
        titleUser = new javax.swing.JLabel();
        passwordTitle = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        editButton = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        idUserText = new javax.swing.JLabel();
        idUserLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        mainTitle.setFont(new java.awt.Font("Sora ExtraBold", 0, 24)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("Edit User");

        titleName.setFont(new java.awt.Font("Sora", 0, 18)); // NOI18N
        titleName.setForeground(new java.awt.Color(255, 255, 255));
        titleName.setText("nome");

        inputName.setBackground(new java.awt.Color(102, 102, 102));
        inputName.setForeground(new java.awt.Color(255, 255, 255));
        inputName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        inputUser.setBackground(new java.awt.Color(102, 102, 102));
        inputUser.setForeground(new java.awt.Color(255, 255, 255));
        inputUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        titleUser.setFont(new java.awt.Font("Sora", 0, 18)); // NOI18N
        titleUser.setForeground(new java.awt.Color(255, 255, 255));
        titleUser.setText("user");

        passwordTitle.setFont(new java.awt.Font("Sora", 0, 18)); // NOI18N
        passwordTitle.setForeground(new java.awt.Color(255, 255, 255));
        passwordTitle.setText("password");

        inputPassword.setBackground(new java.awt.Color(102, 102, 102));
        inputPassword.setForeground(new java.awt.Color(255, 255, 255));
        inputPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        editButton.setBackground(new java.awt.Color(102, 102, 102));
        editButton.setFont(new java.awt.Font("Sora", 0, 18)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 255, 255));
        lblError.setText("All fields are obrigatory.");

        idUserText.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        idUserText.setForeground(new java.awt.Color(255, 255, 255));
        idUserText.setText("idUser:");

        idUserLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        idUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        idUserLabel.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleName)
                            .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleUser)
                            .addComponent(passwordTitle)
                            .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(mainTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(idUserText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idUserLabel)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblError)
                        .addGap(113, 113, 113))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUserText)
                    .addComponent(idUserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleName)
                .addGap(10, 10, 10)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titleUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
            // TODO add your handling code here:
            if(this.inputPassword.getText().length() == 0 || this.inputName.getText().length() == 0||
                    this.inputUser.getText().length() == 0){
                this.lblError.setText("All fields are obrigatory.");
            }else{
                Querys q = new Querys();
                
                q.setName(this.inputName.getText());
                q.setUser(this.inputUser.getText());
                q.setPassword( this.inputPassword.getText());
                q.setId(this.idUserLabel.getText());
                
                
                
               if(UserServices.update(q)){
                   UserServices.setListar("");
                   JOptionPane.showMessageDialog(this, "Dados Atualizados com Sucesso.", "Informação", JOptionPane.INFORMATION_MESSAGE);
               }else{
                   JOptionPane.showMessageDialog(this, "Dados Atualizados com Sucesso.", "Informação", JOptionPane.INFORMATION_MESSAGE);
               }
                this.dispose();
            }

    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormUpdate dialog = new FormUpdate(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editButton;
    public static javax.swing.JLabel idUserLabel;
    private javax.swing.JLabel idUserText;
    public static javax.swing.JTextField inputName;
    public static javax.swing.JPasswordField inputPassword;
    public static javax.swing.JTextField inputUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel titleName;
    private javax.swing.JLabel titleUser;
    // End of variables declaration//GEN-END:variables
}
